### ISSUE TITLE
Unable to handle kernel NULL pointer dereference at virtual address 00000098

### ISSUE THREAD

**Issue by Arturmes** [rsuntk/a03_tmp#1]
I am having error on boot up as described in the title. Can this be avoided?

**Comment by rsuntk** [comment]
Without logs, this problem cannot resolved, but try my other A03 kernel source:
stable (4.14.199): https://github.com/rsuntk/a03
upstreamed (4.14.212): https://github.com/rsuntk/a03/tree/test

if those kernel still cannot boot, well, that's unisoc things (some A03, usually binary version under 5 cannot booted.)

**Comment by Arturmes** [comment]
I will provide logs from the current core
[dmesg-ramoops.txt](https://github.com/rsuntk/android_kernel_samsung_a03/files/15368167/dmesg-ramoops.txt)

**Comment by rsuntk** [comment]
Ramoops says that's Kernel Panic. Same issue with everyone with binary under U/S5. But i will try to fix this

**Comment by Arturmes** [comment]
A possible cause of the kernel panic has been found. Driver drivers/mmc/host/sprd-sdhcr11 If you disable it, the panic disappears, but the kernel freezes in the first seconds of boot

**Comment by rsuntk** [comment]
I will search for references.
